/*
 * This Spock specification was generated by the Gradle 'init' task.
 */
package org.clinicalontology.common.string

import spock.lang.Specification

class StringUtilsTest extends Specification {

    def "capitalize"() {
        setup:
        String string1 = null
        String string2 = ""
        String string3 = "cat"
        String string4 = "cAt"
        String string5 = "'cat'"

        when:
        String string1Cap = StringUtils.capitalize(string1)
        String string2Cap = StringUtils.capitalize(string2)
        String string3Cap = StringUtils.capitalize(string3)
        String string4Cap = StringUtils.capitalize(string4)
        String string5Cap = StringUtils.capitalize(string5)

        then:
        string1Cap == null
        string2Cap == ""
        string3Cap == "Cat"
        string4Cap == "CAt"
        string5Cap == "'cat'"
    }
}
