/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.clinicalontology.common.st;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
